### ISSUE TITLE
The mechanism works also with voice messages, not just with images

### ISSUE THREAD

**Issue by ao2** [iNPUTmice/ImageDownloader#2]
Hi, this is very useful and it should work with other encrypted files too, not just images.
Thanks.

For instance, I can confirm that the same mechanism works with voice messages uploaded by Conversations.

Maybe a better name could be used instead of ImageDownloader, but it's not a big deal.

The wrapper script could also be made more generic by using something like xdg-open;
along the lines of the one I am using for the python port:
https://git.ao2.it/conversations_http_downloader.git/blob/HEAD:/open_wrapper.sh

in this case I guess the file should have to be saved locally, maybe in a temporary file created with `tempfile`.

Also, the script can be converted from bash to be posix shell compliant with very little effort, I can send a patch for that if you want.

**Comment by iNPUTmice** [comment]
This project is more of a tech demo that explains other developers how the
encryption works.
I'm not interested in developing this into a full fledged user stack.
Ideally your client should be able to handle the encryption out of the box.
So either put your energy into your client or maybe fork this project.

**Comment by ao2** [comment]
OK, I understand. I think I can close the issue then.

Thanks again,
   Antonio
